package gregtechmod.loaders.load;

import gregtechmod.GT_Mod;
import gregtechmod.api.util.GT_Log;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class GT_SonictronLoader implements Runnable {

   public void run() {
      GT_Log.out.println("GT_Mod: Loading Sonictron Sounds");
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72083_ai, 1));
      GT_Mod.mSoundNames.add("note.harp");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72105_ah, 1));
      GT_Mod.mSoundNames.add("note.pling");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71981_t, 1));
      GT_Mod.mSoundNames.add("note.bd");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71951_J, 1));
      GT_Mod.mSoundNames.add("note.bassattack");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71988_x, 1));
      GT_Mod.mSoundNames.add("note.bass");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71946_M, 1));
      GT_Mod.mSoundNames.add("note.hat");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71939_E, 1));
      GT_Mod.mSoundNames.add("note.snare");
      GT_Mod.mSoundCounts.add(Integer.valueOf(25));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77797_bJ, 1));
      GT_Mod.mSoundNames.add("streaming.");
      GT_Mod.mSoundCounts.add(Integer.valueOf(12));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72091_am, 1));
      GT_Mod.mSoundNames.add("random.explode");
      GT_Mod.mSoundCounts.add(Integer.valueOf(3));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72067_ar, 1));
      GT_Mod.mSoundNames.add("fire.fire");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77709_i, 1));
      GT_Mod.mSoundNames.add("fire.ignite");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71944_C, 1));
      GT_Mod.mSoundNames.add("liquid.lavapop");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71942_A, 1));
      GT_Mod.mSoundNames.add("liquid.water");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77786_ax, 1));
      GT_Mod.mSoundNames.add("liquid.splash");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77775_ay, 1));
      GT_Mod.mSoundNames.add("random.fizz");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72015_be, 1));
      GT_Mod.mSoundNames.add("portal.portal");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72102_bH, 1));
      GT_Mod.mSoundNames.add("portal.travel");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72104_bI, 1));
      GT_Mod.mSoundNames.add("portal.trigger");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72003_bq, 1));
      GT_Mod.mSoundNames.add("random.glass");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77730_bn, 1));
      GT_Mod.mSoundNames.add("random.orb");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77748_bA, 1));
      GT_Mod.mSoundNames.add("random.levelup");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72034_aR, 1));
      GT_Mod.mSoundNames.add("random.click");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71978_w, 1));
      GT_Mod.mSoundNames.add("damage.fallbig");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71979_v, 1));
      GT_Mod.mSoundNames.add("damage.fallsmall");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77716_q, 1));
      GT_Mod.mSoundNames.add("damage.hurtflesh");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77718_z, 1));
      GT_Mod.mSoundNames.add("random.hurt");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77707_k, 1));
      GT_Mod.mSoundNames.add("random.bow");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77704_l, 1));
      GT_Mod.mSoundNames.add("random.drr");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77749_aR, 1));
      GT_Mod.mSoundNames.add("random.bowhit");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77695_f, 1));
      GT_Mod.mSoundNames.add("random.break");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77788_aw, 1));
      GT_Mod.mSoundNames.add("random.breath");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77726_bs, 1));
      GT_Mod.mSoundNames.add("random.drink");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77729_bt, 1));
      GT_Mod.mSoundNames.add("random.burp");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72066_bS == null?Block.field_72089_ap:Block.field_72066_bS, 1));
      GT_Mod.mSoundNames.add("random.chestopen");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72077_au, 1));
      GT_Mod.mSoundNames.add("random.chestclosed");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77766_aB, 1));
      GT_Mod.mSoundNames.add("random.door_open");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77790_av, 1));
      GT_Mod.mSoundNames.add("random.door_close");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Item.field_77784_aq, 1));
      GT_Mod.mSoundNames.add("random.eat");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72101_ab, 1));
      GT_Mod.mSoundNames.add("step.cloth");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71980_u, 1));
      GT_Mod.mSoundNames.add("step.grass");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71940_F, 1));
      GT_Mod.mSoundNames.add("step.gravel");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72037_aS, 1));
      GT_Mod.mSoundNames.add("step.snow");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71963_Z, 1));
      GT_Mod.mSoundNames.add("tile.piston.out");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71956_V, 1));
      GT_Mod.mSoundNames.add("tile.piston.in");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72087_ao, 1));
      GT_Mod.mSoundNames.add("ambient.cave.cave");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_71948_O, 1));
      GT_Mod.mSoundNames.add("ambient.weather.rain");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
      GT_Mod.mSoundItems.add(new ItemStack(Block.field_72071_ax, 1));
      GT_Mod.mSoundNames.add("ambient.weather.thunder");
      GT_Mod.mSoundCounts.add(Integer.valueOf(1));
   }
}
