package gregtechmod.loaders.preload;

import gregtechmod.api.GregTech_API;
import gregtechmod.api.enums.GT_Items;
import gregtechmod.api.enums.GT_OreDictNames;
import gregtechmod.api.enums.Materials;
import gregtechmod.api.enums.OrePrefixes;
import gregtechmod.api.util.GT_Log;
import gregtechmod.api.util.GT_ModHandler;
import gregtechmod.api.util.GT_OreDictUnificator;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class GT_DictRegistratorPreItem implements Runnable {

   public void run() {
      GT_Log.out.println("GT_Mod: Register OreDict Entries of Non-GT-Items.");
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Empty, GT_Items.Cell_Empty.get(1L, new Object[0]));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Oxygen, GT_Items.Cell_Air.get(1L, new Object[0]));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Oxygen, GT_ModHandler.getIC2Item("airCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Lava, GT_Items.Cell_Lava.get(1L, new Object[0]));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Lava, GT_ModHandler.getIC2Item("lavaCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Water, GT_Items.Cell_Water.get(1L, new Object[0]));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Water, GT_ModHandler.getIC2Item("waterCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.Creosote, GT_ModHandler.getRCItem("fluid.creosote.cell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.BioFuel, GT_ModHandler.getIC2Item("biofuelCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.CoalFuel, GT_ModHandler.getIC2Item("coalfuelCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.UUMatter, GT_ModHandler.getIC2Item("UuMatterCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.cell, Materials.ConstructionFoam, GT_ModHandler.getIC2Item("CFCell", 1L));
      GT_OreDictUnificator.set(OrePrefixes.bucket, Materials.Empty, new ItemStack(Item.field_77788_aw, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.bucket, Materials.Water, new ItemStack(Item.field_77786_ax, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.bucket, Materials.Lava, new ItemStack(Item.field_77775_ay, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.bottle, Materials.Empty, new ItemStack(Item.field_77729_bt, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.bottle, Materials.Water, new ItemStack(Item.field_77726_bs, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.plateAlloy, Materials.Iridium, GT_ModHandler.getIC2Item("iridiumPlate", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateAlloy, Materials.Advanced, GT_ModHandler.getIC2Item("advancedAlloy", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateAlloy, Materials.Carbon, GT_ModHandler.getIC2Item("carbonPlate", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Copper, GT_ModHandler.getIC2Item("denseCopperPlate", 1L, GT_ModHandler.getIC2Item("denseplatecopper", 1L)));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Tin, GT_ModHandler.getIC2Item("denseplatetin", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Bronze, GT_ModHandler.getIC2Item("denseplatebronze", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Gold, GT_ModHandler.getIC2Item("denseplategold", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Iron, GT_ModHandler.getIC2Item("denseplateiron", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Iron, GT_ModHandler.getIC2Item("denseplateadviron", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Lead, GT_ModHandler.getIC2Item("denseplatelead", 1L));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Lapis, GT_ModHandler.getIC2Item("denseplatelapi", 1L, GT_ModHandler.getIC2Item("denseplatelapis", 1L)));
      GT_OreDictUnificator.set(OrePrefixes.plateDense, Materials.Obsidian, GT_ModHandler.getIC2Item("denseplateobsidian", 1L));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Coal, new ItemStack(Block.field_71950_I, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Iron, new ItemStack(Block.field_71949_H, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Lapis, new ItemStack(Block.field_71947_N, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Redstone, new ItemStack(Block.field_72048_aO, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Redstone, new ItemStack(Block.field_72047_aN, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Gold, new ItemStack(Block.field_71941_G, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Diamond, new ItemStack(Block.field_72073_aw, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Emerald, new ItemStack(Block.field_72068_bR, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.NetherQuartz, new ItemStack(Block.field_94342_cr, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Galena, new ItemStack(GregTech_API.sBlockList[2], 1, 1));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Iridium, new ItemStack(GregTech_API.sBlockList[2], 1, 2));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Ruby, new ItemStack(GregTech_API.sBlockList[2], 1, 3));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Sapphire, new ItemStack(GregTech_API.sBlockList[2], 1, 4));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Bauxite, new ItemStack(GregTech_API.sBlockList[2], 1, 5));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Pyrite, new ItemStack(GregTech_API.sBlockList[2], 1, 6));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Cinnabar, new ItemStack(GregTech_API.sBlockList[2], 1, 7));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Sphalerite, new ItemStack(GregTech_API.sBlockList[2], 1, 8));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Tungstate, new ItemStack(GregTech_API.sBlockList[2], 1, 9));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Cooperite, new ItemStack(GregTech_API.sBlockList[2], 1, 10));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Olivine, new ItemStack(GregTech_API.sBlockList[2], 1, 11));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Sodalite, new ItemStack(GregTech_API.sBlockList[2], 1, 12));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Tetrahedrite, new ItemStack(GregTech_API.sBlockList[2], 1, 13));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Cassiterite, new ItemStack(GregTech_API.sBlockList[2], 1, 14));
      GT_OreDictUnificator.set(OrePrefixes.ore, Materials.Nickel, new ItemStack(GregTech_API.sBlockList[2], 1, 15));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Copper, GT_ModHandler.getIC2Item("copperIngot", 1L));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Tin, GT_ModHandler.getIC2Item("tinIngot", 1L));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Lead, GT_ModHandler.getIC2Item("leadIngot", 1L));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Bronze, GT_ModHandler.getIC2Item("bronzeIngot", 1L));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Silver, GT_ModHandler.getIC2Item("silverIngot", 1L));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Iridium, GT_ModHandler.getIC2Item("iridiumOre", 1L));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.EnderEye, new ItemStack(Item.field_77748_bA, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.EnderPearl, new ItemStack(Item.field_77730_bn, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Diamond, new ItemStack(Item.field_77702_n, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Emerald, new ItemStack(Item.field_77817_bH, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Coal, new ItemStack(Item.field_77705_m, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Charcoal, new ItemStack(Item.field_77705_m, 1, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.Lapis, new ItemStack(Item.field_77756_aW, 1, 4));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.NetherQuartz, new ItemStack(Item.field_94583_ca, 1));
      GT_OreDictUnificator.set(OrePrefixes.gem, Materials.NetherStar, new ItemStack(Item.field_82792_bS, 1));
      GT_OreDictUnificator.set(OrePrefixes.nugget, Materials.Gold, new ItemStack(Item.field_77733_bq, 1));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Gold, new ItemStack(Item.field_77717_p, 1));
      GT_OreDictUnificator.set(OrePrefixes.ingot, Materials.Iron, new ItemStack(Item.field_77703_o, 1));
      GT_OreDictUnificator.set(OrePrefixes.plate, Materials.Paper, new ItemStack(Item.field_77759_aK, 1));
      GT_OreDictUnificator.set(OrePrefixes.dust, Materials.Sugar, new ItemStack(Item.field_77747_aY, 1));
      GT_OreDictUnificator.set(OrePrefixes.stick, Materials.Wood, new ItemStack(Item.field_77669_D, 1));
      GT_OreDictUnificator.set(OrePrefixes.dust, Materials.Redstone, new ItemStack(Item.field_77767_aC, 1));
      GT_OreDictUnificator.set(OrePrefixes.dust, Materials.Gunpowder, new ItemStack(Item.field_77677_M, 1));
      GT_OreDictUnificator.set(OrePrefixes.dust, Materials.Glowstone, new ItemStack(Item.field_77751_aT, 1));
      GT_OreDictUnificator.set(OrePrefixes.dust, Materials.Blaze, new ItemStack(Item.field_77722_bw, 1));
      GT_OreDictUnificator.set(OrePrefixes.stick, Materials.Blaze, new ItemStack(Item.field_77731_bo, 1));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Iron, new ItemStack(Block.field_72083_ai, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Gold, new ItemStack(Block.field_72105_ah, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Diamond, new ItemStack(Block.field_72071_ax, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Emerald, new ItemStack(Block.field_72076_bV, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Lapis, new ItemStack(Block.field_71948_O, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Coal, new ItemStack(Block.field_111034_cE, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Redstone, new ItemStack(Block.field_94341_cq, 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Silver, new ItemStack(GregTech_API.sBlockList[0], 1, 3));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Ruby, new ItemStack(GregTech_API.sBlockList[0], 1, 4));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Sapphire, new ItemStack(GregTech_API.sBlockList[0], 1, 5));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Aluminium, new ItemStack(GregTech_API.sBlockList[0], 1, 7));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Titanium, new ItemStack(GregTech_API.sBlockList[0], 1, 8));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Chrome, new ItemStack(GregTech_API.sBlockList[0], 1, 9));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Steel, new ItemStack(GregTech_API.sBlockList[0], 1, 11));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Brass, new ItemStack(GregTech_API.sBlockList[0], 1, 12));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Lead, new ItemStack(GregTech_API.sBlockList[4], 1, 0));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Electrum, new ItemStack(GregTech_API.sBlockList[4], 1, 1));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Zinc, new ItemStack(GregTech_API.sBlockList[4], 1, 2));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Olivine, new ItemStack(GregTech_API.sBlockList[4], 1, 3));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.GreenSapphire, new ItemStack(GregTech_API.sBlockList[4], 1, 4));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Platinum, new ItemStack(GregTech_API.sBlockList[4], 1, 5));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Tungsten, new ItemStack(GregTech_API.sBlockList[4], 1, 6));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Nickel, new ItemStack(GregTech_API.sBlockList[4], 1, 7));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Invar, new ItemStack(GregTech_API.sBlockList[4], 1, 10));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Osmium, new ItemStack(GregTech_API.sBlockList[4], 1, 11));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.Iridium, new ItemStack(GregTech_API.sBlockList[4], 1, 12));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.GarnetYellow, new ItemStack(GregTech_API.sBlockList[4], 1, 14));
      GT_OreDictUnificator.set(OrePrefixes.block, Materials.GarnetRed, new ItemStack(GregTech_API.sBlockList[4], 1, 15));
      if(Block.field_72066_bS != null) {
         GT_OreDictUnificator.registerOre(GT_OreDictNames.craftingEnderChest, new ItemStack(Block.field_72066_bS, 1));
      }

      GT_OreDictUnificator.registerOre(GT_OreDictNames.craftingIndustrialDiamond, GT_Items.IC2_Industrial_Diamond.get(1L, new Object[0]));
      GT_OreDictUnificator.registerOre(OrePrefixes.dust, Materials.Wood, GT_ModHandler.getTEItem("sawdust", 1L));
      GT_OreDictUnificator.registerOre(OrePrefixes.glass, Materials.Reinforced, GT_ModHandler.getIC2Item("reinforcedGlass", 1L));
      GT_OreDictUnificator.registerOre(OrePrefixes.glass, Materials.Reinforced, GT_ModHandler.getTEItem("glassHardened", 1L));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Basalt, GT_ModHandler.getRCItem("cube.stone.abyssal", 1L));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Marble, GT_ModHandler.getRCItem("cube.stone.quarried", 1L));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Obsidian, new ItemStack(Block.field_72089_ap, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneMossy, new ItemStack(Block.field_72087_ao, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneCobble, new ItemStack(Block.field_72087_ao, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneCobble, new ItemStack(Block.field_71978_w, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneSmooth, new ItemStack(Block.field_71981_t, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneBricks, new ItemStack(Block.field_72007_bm, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneMossy, new ItemStack(Block.field_72007_bm, 1, 1));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneCracked, new ItemStack(Block.field_72007_bm, 1, 2));
      GT_OreDictUnificator.registerOre(OrePrefixes.stoneChiseled, new ItemStack(Block.field_72007_bm, 1, 3));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Sand, new ItemStack(Block.field_71957_Q, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Netherrack, new ItemStack(Block.field_72012_bb, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.NetherBrick, new ItemStack(Block.field_72033_bA, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.Endstone, new ItemStack(Block.field_72082_bJ, 1, 32767));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 0));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 1));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 2));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 3));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 4));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 5));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 6));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteBlack, new ItemStack(GregTech_API.sBlockList[5], 1, 7));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 8));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 9));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 10));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 11));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 12));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 13));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 14));
      GT_OreDictUnificator.registerOre(OrePrefixes.stone, Materials.GraniteRed, new ItemStack(GregTech_API.sBlockList[5], 1, 15));
   }
}
