package gregtechmod.api.enums;

import gregtechmod.api.GregTech_API;
import gregtechmod.api.interfaces.IIconContainer;
import gregtechmod.api.util.GT_Config;
import net.minecraft.client.renderer.texture.IconRegister;
import net.minecraft.util.Icon;

public class GT_ItemTextures implements Runnable {

   public static final IIconContainer[] SET_LAPIS = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_LAPIS, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_QUARTZ = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_QUARTZ, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_POWDER = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_POWDER, GT_ItemTextures.MetaIcons.DUST_SMALL_POWDER, GT_ItemTextures.MetaIcons.DUST_POWDER, GT_ItemTextures.MetaIcons.DUST_IMPURE_POWDER, GT_ItemTextures.MetaIcons.DUST_PURE_POWDER, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_LIGNITE = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_ROUGH, GT_ItemTextures.MetaIcons.DUST_SMALL_ROUGH, GT_ItemTextures.MetaIcons.DUST_ROUGH, GT_ItemTextures.MetaIcons.DUST_IMPURE_ROUGH, GT_ItemTextures.MetaIcons.DUST_PURE_ROUGH, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_LIGNITE, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_SAND = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_SAND, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED_SAND, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_FINE = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_ROUGH = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_ROUGH, GT_ItemTextures.MetaIcons.DUST_SMALL_ROUGH, GT_ItemTextures.MetaIcons.DUST_ROUGH, GT_ItemTextures.MetaIcons.DUST_IMPURE_ROUGH, GT_ItemTextures.MetaIcons.DUST_PURE_ROUGH, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LAPIS, GT_ItemTextures.MetaIcons.PLATE_DENSE_LAPIS, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_METALLIC = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_METALLIC, GT_ItemTextures.MetaIcons.DUST_SMALL_METALLIC, GT_ItemTextures.MetaIcons.DUST_METALLIC, GT_ItemTextures.MetaIcons.DUST_IMPURE_METALLIC, GT_ItemTextures.MetaIcons.DUST_PURE_METALLIC, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_METALLIC, null, GT_ItemTextures.MetaIcons.INGOT_METALLIC, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_METALLIC, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_METALLIC, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_METALLIC, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_METALLIC, GT_ItemTextures.MetaIcons.PLATE_DENSE_METALLIC, GT_ItemTextures.MetaIcons.ROD_METALLIC, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_METALLIC};
   public static final IIconContainer[] SET_FLINT = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_ROUGH, GT_ItemTextures.MetaIcons.DUST_SMALL_ROUGH, GT_ItemTextures.MetaIcons.DUST_ROUGH, GT_ItemTextures.MetaIcons.DUST_IMPURE_ROUGH, GT_ItemTextures.MetaIcons.DUST_PURE_ROUGH, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_FLINT, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_DULL, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_DULL, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_DENSE_DULL, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_DIAMOND = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_DIAMOND, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_OPAL = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_OPAL, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_RUBY = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_RUBY, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_GEM_HORIZONTAL = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_RECTANGLE_HORIZONTAL, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_GEM_VERTICAL = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_RECTANGLE_VERTICAL, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_NETHERSTAR = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_NETHERSTAR, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_EMERALD = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_EMERALD, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_SHINY = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_SHINY, GT_ItemTextures.MetaIcons.DUST_SMALL_SHINY, GT_ItemTextures.MetaIcons.DUST_SHINY, GT_ItemTextures.MetaIcons.DUST_IMPURE_SHINY, GT_ItemTextures.MetaIcons.DUST_PURE_SHINY, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_SHINY, null, GT_ItemTextures.MetaIcons.INGOT_SHINY, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_SHINY, GT_ItemTextures.MetaIcons.PLATE_DENSE_SHINY, GT_ItemTextures.MetaIcons.ROD_SHINY, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_SHINY};
   public static final IIconContainer[] SET_DULL = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_DULL, GT_ItemTextures.MetaIcons.DUST_SMALL_DULL, GT_ItemTextures.MetaIcons.DUST_DULL, GT_ItemTextures.MetaIcons.DUST_IMPURE_DULL, GT_ItemTextures.MetaIcons.DUST_PURE_DULL, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_DULL, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_DULL, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_DULL, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_DENSE_DULL, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_METALLIC};
   public static final IIconContainer[] SET_PAPER = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_LEAF, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_PAPER, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_PAPER, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_PAPER, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_PAPER, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_PAPER, GT_ItemTextures.MetaIcons.PLATE_DENSE_PAPER, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_STONE};
   public static final IIconContainer[] SET_WOOD = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_LEAF, null, GT_ItemTextures.MetaIcons.INGOT_DULL, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_DULL, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_DULL, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_DULL, GT_ItemTextures.MetaIcons.PLATE_WOOD, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_WOOD, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_WOOD, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_WOOD, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_WOOD, GT_ItemTextures.MetaIcons.PLATE_DENSE_WOOD, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_WOOD};
   public static final IIconContainer[] SET_LEAF = new IIconContainer[]{GT_ItemTextures.MetaIcons.DUST_TINY_FINE, GT_ItemTextures.MetaIcons.DUST_SMALL_FINE, GT_ItemTextures.MetaIcons.DUST_FINE, GT_ItemTextures.MetaIcons.DUST_IMPURE_FINE, GT_ItemTextures.MetaIcons.DUST_PURE_FINE, GT_ItemTextures.MetaIcons.CRUSHED, GT_ItemTextures.MetaIcons.PURIFIED, GT_ItemTextures.MetaIcons.CENTRIFUGED, GT_ItemTextures.MetaIcons.GEM_METALLIC, GT_ItemTextures.MetaIcons.NUGGET_LEAF, null, GT_ItemTextures.MetaIcons.INGOT_LEAF, GT_ItemTextures.MetaIcons.INGOT_HOT, GT_ItemTextures.MetaIcons.INGOT_DOUBLE_LEAF, GT_ItemTextures.MetaIcons.INGOT_TRIPLE_LEAF, GT_ItemTextures.MetaIcons.INGOT_QUADRUPLE_LEAF, GT_ItemTextures.MetaIcons.INGOT_QUINTUPLE_LEAF, GT_ItemTextures.MetaIcons.PLATE_LEAF, GT_ItemTextures.MetaIcons.PLATE_DOUBLE_LEAF, GT_ItemTextures.MetaIcons.PLATE_TRIPLE_LEAF, GT_ItemTextures.MetaIcons.PLATE_QUADRUPLE_LEAF, GT_ItemTextures.MetaIcons.PLATE_QUINTUPLE_LEAF, GT_ItemTextures.MetaIcons.PLATE_DENSE_LEAF, GT_ItemTextures.MetaIcons.ROD_DULL, GT_ItemTextures.MetaIcons.LENS, GT_ItemTextures.MetaIcons.ROUND, GT_ItemTextures.MetaIcons.BOLT, GT_ItemTextures.MetaIcons.SCREW, GT_ItemTextures.MetaIcons.RING, null, GT_ItemTextures.MetaIcons.CELL, GT_ItemTextures.MetaIcons.CELL_PLASMA, GT_ItemTextures.MetaIcons.TOOLHEAD_SWORD, GT_ItemTextures.MetaIcons.TOOLHEAD_PICKAXE, GT_ItemTextures.MetaIcons.TOOLHEAD_SHOVEL, GT_ItemTextures.MetaIcons.TOOLHEAD_AXE, GT_ItemTextures.MetaIcons.TOOLHEAD_HOE, GT_ItemTextures.MetaIcons.TOOLHEAD_HAMMER, GT_ItemTextures.MetaIcons.TOOLHEAD_FILE, GT_ItemTextures.MetaIcons.TOOLHEAD_SAW, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.GEAR_WOOD};
   public static final IIconContainer[] SET_EMPTY = new IIconContainer[]{null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, GT_ItemTextures.MetaIcons.CELL_EMPTY, GT_ItemTextures.MetaIcons.CELL_EMPTY, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null};
   public static final IIconContainer[] SET_NONE = SET_DULL;
   public static final IIconContainer[] SET_FLUID = SET_DULL;


   public GT_ItemTextures() {
      GregTech_API.sGTItemIconload.add(this);
   }

   public void run() {
      GT_ItemTextures.MetaIcons[] arr$ = GT_ItemTextures.MetaIcons.values();
      int len$ = arr$.length;

      for(int i$ = 0; i$ < len$; ++i$) {
         GT_ItemTextures.MetaIcons tIcon = arr$[i$];
         tIcon.mIcon = ((IconRegister)GregTech_API.sItemIcons).func_94245_a("gregtech_addon:" + (GT_Config.system?"troll":"iconsets/" + tIcon));
         tIcon.mOverlay = ((IconRegister)GregTech_API.sItemIcons).func_94245_a("gregtech_addon:" + (GT_Config.system?"troll":"iconsets/" + tIcon + "_OVERLAY"));
      }

   }


   public static enum MetaIcons implements IIconContainer {

      VOID("VOID", 0),
      INGOT_METALLIC("INGOT_METALLIC", 1),
      INGOT_SHINY("INGOT_SHINY", 2),
      INGOT_DULL("INGOT_DULL", 3),
      INGOT_LEAF("INGOT_LEAF", 4),
      INGOT_HOT("INGOT_HOT", 5),
      INGOT_DOUBLE_METALLIC("INGOT_DOUBLE_METALLIC", 6),
      INGOT_DOUBLE_SHINY("INGOT_DOUBLE_SHINY", 7),
      INGOT_DOUBLE_DULL("INGOT_DOUBLE_DULL", 8),
      INGOT_DOUBLE_LEAF("INGOT_DOUBLE_LEAF", 9),
      INGOT_TRIPLE_METALLIC("INGOT_TRIPLE_METALLIC", 10),
      INGOT_TRIPLE_SHINY("INGOT_TRIPLE_SHINY", 11),
      INGOT_TRIPLE_DULL("INGOT_TRIPLE_DULL", 12),
      INGOT_TRIPLE_LEAF("INGOT_TRIPLE_LEAF", 13),
      INGOT_QUADRUPLE_METALLIC("INGOT_QUADRUPLE_METALLIC", 14),
      INGOT_QUADRUPLE_SHINY("INGOT_QUADRUPLE_SHINY", 15),
      INGOT_QUADRUPLE_DULL("INGOT_QUADRUPLE_DULL", 16),
      INGOT_QUADRUPLE_LEAF("INGOT_QUADRUPLE_LEAF", 17),
      INGOT_QUINTUPLE_METALLIC("INGOT_QUINTUPLE_METALLIC", 18),
      INGOT_QUINTUPLE_SHINY("INGOT_QUINTUPLE_SHINY", 19),
      INGOT_QUINTUPLE_DULL("INGOT_QUINTUPLE_DULL", 20),
      INGOT_QUINTUPLE_LEAF("INGOT_QUINTUPLE_LEAF", 21),
      PLATE_METALLIC("PLATE_METALLIC", 22),
      PLATE_SHINY("PLATE_SHINY", 23),
      PLATE_DULL("PLATE_DULL", 24),
      PLATE_LEAF("PLATE_LEAF", 25),
      PLATE_LAPIS("PLATE_LAPIS", 26),
      PLATE_WOOD("PLATE_WOOD", 27),
      PLATE_PAPER("PLATE_PAPER", 28),
      PLATE_DOUBLE_METALLIC("PLATE_DOUBLE_METALLIC", 29),
      PLATE_DOUBLE_SHINY("PLATE_DOUBLE_SHINY", 30),
      PLATE_DOUBLE_DULL("PLATE_DOUBLE_DULL", 31),
      PLATE_DOUBLE_LEAF("PLATE_DOUBLE_LEAF", 32),
      PLATE_DOUBLE_LAPIS("PLATE_DOUBLE_LAPIS", 33),
      PLATE_DOUBLE_WOOD("PLATE_DOUBLE_WOOD", 34),
      PLATE_DOUBLE_PAPER("PLATE_DOUBLE_PAPER", 35),
      PLATE_TRIPLE_METALLIC("PLATE_TRIPLE_METALLIC", 36),
      PLATE_TRIPLE_SHINY("PLATE_TRIPLE_SHINY", 37),
      PLATE_TRIPLE_DULL("PLATE_TRIPLE_DULL", 38),
      PLATE_TRIPLE_LEAF("PLATE_TRIPLE_LEAF", 39),
      PLATE_TRIPLE_LAPIS("PLATE_TRIPLE_LAPIS", 40),
      PLATE_TRIPLE_WOOD("PLATE_TRIPLE_WOOD", 41),
      PLATE_TRIPLE_PAPER("PLATE_TRIPLE_PAPER", 42),
      PLATE_QUADRUPLE_METALLIC("PLATE_QUADRUPLE_METALLIC", 43),
      PLATE_QUADRUPLE_SHINY("PLATE_QUADRUPLE_SHINY", 44),
      PLATE_QUADRUPLE_DULL("PLATE_QUADRUPLE_DULL", 45),
      PLATE_QUADRUPLE_LEAF("PLATE_QUADRUPLE_LEAF", 46),
      PLATE_QUADRUPLE_LAPIS("PLATE_QUADRUPLE_LAPIS", 47),
      PLATE_QUADRUPLE_WOOD("PLATE_QUADRUPLE_WOOD", 48),
      PLATE_QUADRUPLE_PAPER("PLATE_QUADRUPLE_PAPER", 49),
      PLATE_QUINTUPLE_METALLIC("PLATE_QUINTUPLE_METALLIC", 50),
      PLATE_QUINTUPLE_SHINY("PLATE_QUINTUPLE_SHINY", 51),
      PLATE_QUINTUPLE_DULL("PLATE_QUINTUPLE_DULL", 52),
      PLATE_QUINTUPLE_LEAF("PLATE_QUINTUPLE_LEAF", 53),
      PLATE_QUINTUPLE_LAPIS("PLATE_QUINTUPLE_LAPIS", 54),
      PLATE_QUINTUPLE_WOOD("PLATE_QUINTUPLE_WOOD", 55),
      PLATE_QUINTUPLE_PAPER("PLATE_QUINTUPLE_PAPER", 56),
      PLATE_DENSE_METALLIC("PLATE_DENSE_METALLIC", 57),
      PLATE_DENSE_SHINY("PLATE_DENSE_SHINY", 58),
      PLATE_DENSE_DULL("PLATE_DENSE_DULL", 59),
      PLATE_DENSE_LEAF("PLATE_DENSE_LEAF", 60),
      PLATE_DENSE_LAPIS("PLATE_DENSE_LAPIS", 61),
      PLATE_DENSE_WOOD("PLATE_DENSE_WOOD", 62),
      PLATE_DENSE_PAPER("PLATE_DENSE_PAPER", 63),
      ROD_METALLIC("ROD_METALLIC", 64),
      ROD_SHINY("ROD_SHINY", 65),
      ROD_DULL("ROD_DULL", 66),
      NUGGET_METALLIC("NUGGET_METALLIC", 67),
      NUGGET_SHINY("NUGGET_SHINY", 68),
      NUGGET_DULL("NUGGET_DULL", 69),
      NUGGET_LEAF("NUGGET_LEAF", 70),
      GEM_METALLIC("GEM_METALLIC", 71),
      GEM_OPAL("GEM_OPAL", 72),
      GEM_FLINT("GEM_FLINT", 73),
      GEM_RUBY("GEM_RUBY", 74),
      GEM_SMALL("GEM_SMALL", 75),
      GEM_LIGNITE("GEM_LIGNITE", 76),
      GEM_ROUND("GEM_ROUND", 77),
      GEM_SQUARE("GEM_SQUARE", 78),
      GEM_OCTAGON("GEM_OCTAGON", 79),
      GEM_QUARTZ("GEM_QUARTZ", 80),
      GEM_LAPIS("GEM_LAPIS", 81),
      GEM_NETHERSTAR("GEM_NETHERSTAR", 82),
      GEM_DIAMOND("GEM_DIAMOND", 83),
      GEM_EMERALD("GEM_EMERALD", 84),
      GEM_RECTANGLE_VERTICAL("GEM_RECTANGLE_VERTICAL", 85),
      GEM_RECTANGLE_HORIZONTAL("GEM_RECTANGLE_HORIZONTAL", 86),
      DUST_METALLIC("DUST_METALLIC", 87),
      DUST_SHINY("DUST_SHINY", 88),
      DUST_ROUGH("DUST_ROUGH", 89),
      DUST_FINE("DUST_FINE", 90),
      DUST_DULL("DUST_DULL", 91),
      DUST_POWDER("DUST_POWDER", 92),
      DUST_IMPURE_METALLIC("DUST_IMPURE_METALLIC", 93),
      DUST_IMPURE_SHINY("DUST_IMPURE_SHINY", 94),
      DUST_IMPURE_ROUGH("DUST_IMPURE_ROUGH", 95),
      DUST_IMPURE_FINE("DUST_IMPURE_FINE", 96),
      DUST_IMPURE_DULL("DUST_IMPURE_DULL", 97),
      DUST_IMPURE_POWDER("DUST_IMPURE_POWDER", 98),
      DUST_IMPURE_SAND("DUST_IMPURE_SAND", 99),
      DUST_PURE_METALLIC("DUST_PURE_METALLIC", 100),
      DUST_PURE_SHINY("DUST_PURE_SHINY", 101),
      DUST_PURE_ROUGH("DUST_PURE_ROUGH", 102),
      DUST_PURE_FINE("DUST_PURE_FINE", 103),
      DUST_PURE_DULL("DUST_PURE_DULL", 104),
      DUST_PURE_POWDER("DUST_PURE_POWDER", 105),
      DUST_SMALL_METALLIC("DUST_SMALL_METALLIC", 106),
      DUST_SMALL_SHINY("DUST_SMALL_SHINY", 107),
      DUST_SMALL_ROUGH("DUST_SMALL_ROUGH", 108),
      DUST_SMALL_FINE("DUST_SMALL_FINE", 109),
      DUST_SMALL_DULL("DUST_SMALL_DULL", 110),
      DUST_SMALL_POWDER("DUST_SMALL_POWDER", 111),
      DUST_TINY_METALLIC("DUST_TINY_METALLIC", 112),
      DUST_TINY_SHINY("DUST_TINY_SHINY", 113),
      DUST_TINY_ROUGH("DUST_TINY_ROUGH", 114),
      DUST_TINY_FINE("DUST_TINY_FINE", 115),
      DUST_TINY_DULL("DUST_TINY_DULL", 116),
      DUST_TINY_POWDER("DUST_TINY_POWDER", 117),
      CRUSHED("CRUSHED", 118),
      CRUSHED_SAND("CRUSHED_SAND", 119),
      PURIFIED("PURIFIED", 120),
      CENTRIFUGED("CENTRIFUGED", 121),
      LENS("LENS", 122),
      ROUND("ROUND", 123),
      BOLT("BOLT", 124),
      SCREW("SCREW", 125),
      RING("RING", 126),
      CELL("CELL", 127),
      CELL_EMPTY("CELL_EMPTY", 128),
      CELL_PLASMA("CELL_PLASMA", 129),
      TOOLHEAD_SWORD("TOOLHEAD_SWORD", 130),
      TOOLHEAD_PICKAXE("TOOLHEAD_PICKAXE", 131),
      TOOLHEAD_SHOVEL("TOOLHEAD_SHOVEL", 132),
      TOOLHEAD_AXE("TOOLHEAD_AXE", 133),
      TOOLHEAD_HOE("TOOLHEAD_HOE", 134),
      TOOLHEAD_HAMMER("TOOLHEAD_HAMMER", 135),
      TOOLHEAD_FILE("TOOLHEAD_FILE", 136),
      TOOLHEAD_SAW("TOOLHEAD_SAW", 137),
      GEAR_METALLIC("GEAR_METALLIC", 138),
      GEAR_SHINY("GEAR_SHINY", 139),
      GEAR_STONE("GEAR_STONE", 140),
      GEAR_WOOD("GEAR_WOOD", 141);
      protected Icon mIcon;
      protected Icon mOverlay;
      // $FF: synthetic field
      private static final GT_ItemTextures.MetaIcons[] $VALUES = new GT_ItemTextures.MetaIcons[]{VOID, INGOT_METALLIC, INGOT_SHINY, INGOT_DULL, INGOT_LEAF, INGOT_HOT, INGOT_DOUBLE_METALLIC, INGOT_DOUBLE_SHINY, INGOT_DOUBLE_DULL, INGOT_DOUBLE_LEAF, INGOT_TRIPLE_METALLIC, INGOT_TRIPLE_SHINY, INGOT_TRIPLE_DULL, INGOT_TRIPLE_LEAF, INGOT_QUADRUPLE_METALLIC, INGOT_QUADRUPLE_SHINY, INGOT_QUADRUPLE_DULL, INGOT_QUADRUPLE_LEAF, INGOT_QUINTUPLE_METALLIC, INGOT_QUINTUPLE_SHINY, INGOT_QUINTUPLE_DULL, INGOT_QUINTUPLE_LEAF, PLATE_METALLIC, PLATE_SHINY, PLATE_DULL, PLATE_LEAF, PLATE_LAPIS, PLATE_WOOD, PLATE_PAPER, PLATE_DOUBLE_METALLIC, PLATE_DOUBLE_SHINY, PLATE_DOUBLE_DULL, PLATE_DOUBLE_LEAF, PLATE_DOUBLE_LAPIS, PLATE_DOUBLE_WOOD, PLATE_DOUBLE_PAPER, PLATE_TRIPLE_METALLIC, PLATE_TRIPLE_SHINY, PLATE_TRIPLE_DULL, PLATE_TRIPLE_LEAF, PLATE_TRIPLE_LAPIS, PLATE_TRIPLE_WOOD, PLATE_TRIPLE_PAPER, PLATE_QUADRUPLE_METALLIC, PLATE_QUADRUPLE_SHINY, PLATE_QUADRUPLE_DULL, PLATE_QUADRUPLE_LEAF, PLATE_QUADRUPLE_LAPIS, PLATE_QUADRUPLE_WOOD, PLATE_QUADRUPLE_PAPER, PLATE_QUINTUPLE_METALLIC, PLATE_QUINTUPLE_SHINY, PLATE_QUINTUPLE_DULL, PLATE_QUINTUPLE_LEAF, PLATE_QUINTUPLE_LAPIS, PLATE_QUINTUPLE_WOOD, PLATE_QUINTUPLE_PAPER, PLATE_DENSE_METALLIC, PLATE_DENSE_SHINY, PLATE_DENSE_DULL, PLATE_DENSE_LEAF, PLATE_DENSE_LAPIS, PLATE_DENSE_WOOD, PLATE_DENSE_PAPER, ROD_METALLIC, ROD_SHINY, ROD_DULL, NUGGET_METALLIC, NUGGET_SHINY, NUGGET_DULL, NUGGET_LEAF, GEM_METALLIC, GEM_OPAL, GEM_FLINT, GEM_RUBY, GEM_SMALL, GEM_LIGNITE, GEM_ROUND, GEM_SQUARE, GEM_OCTAGON, GEM_QUARTZ, GEM_LAPIS, GEM_NETHERSTAR, GEM_DIAMOND, GEM_EMERALD, GEM_RECTANGLE_VERTICAL, GEM_RECTANGLE_HORIZONTAL, DUST_METALLIC, DUST_SHINY, DUST_ROUGH, DUST_FINE, DUST_DULL, DUST_POWDER, DUST_IMPURE_METALLIC, DUST_IMPURE_SHINY, DUST_IMPURE_ROUGH, DUST_IMPURE_FINE, DUST_IMPURE_DULL, DUST_IMPURE_POWDER, DUST_IMPURE_SAND, DUST_PURE_METALLIC, DUST_PURE_SHINY, DUST_PURE_ROUGH, DUST_PURE_FINE, DUST_PURE_DULL, DUST_PURE_POWDER, DUST_SMALL_METALLIC, DUST_SMALL_SHINY, DUST_SMALL_ROUGH, DUST_SMALL_FINE, DUST_SMALL_DULL, DUST_SMALL_POWDER, DUST_TINY_METALLIC, DUST_TINY_SHINY, DUST_TINY_ROUGH, DUST_TINY_FINE, DUST_TINY_DULL, DUST_TINY_POWDER, CRUSHED, CRUSHED_SAND, PURIFIED, CENTRIFUGED, LENS, ROUND, BOLT, SCREW, RING, CELL, CELL_EMPTY, CELL_PLASMA, TOOLHEAD_SWORD, TOOLHEAD_PICKAXE, TOOLHEAD_SHOVEL, TOOLHEAD_AXE, TOOLHEAD_HOE, TOOLHEAD_HAMMER, TOOLHEAD_FILE, TOOLHEAD_SAW, GEAR_METALLIC, GEAR_SHINY, GEAR_STONE, GEAR_WOOD};


      private MetaIcons(String var1, int var2) {}

      public Icon getIcon() {
         return this.mIcon;
      }

      public Icon getOverlayIcon() {
         return this.mOverlay;
      }

      public int getOverlayX() {
         return 0;
      }

      public int getOverlayY() {
         return 0;
      }

      public int getOverlayWidth() {
         return 16;
      }

      public int getOverlayHeight() {
         return 16;
      }

   }
}
