package gregtechmod.loaders.postload;

import gregtechmod.api.GregTech_API;
import gregtechmod.api.enums.GT_ConfigCategories;
import gregtechmod.api.enums.GT_Items;
import gregtechmod.api.enums.Materials;
import gregtechmod.api.enums.OrePrefixes;
import gregtechmod.api.util.GT_Log;
import gregtechmod.api.util.GT_ModHandler;
import gregtechmod.api.util.GT_OreDictUnificator;
import gregtechmod.api.util.GT_RecipeRegistrator;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class GT_RecyclingRecipeLoader implements Runnable {

   public void run() {
      GT_Log.out.println("GT_Mod: Adding all the Reverse Recipes for the Furnace/Macerator/Sawmill.");
      if(!GregTech_API.sRecipeFile.get(GT_ConfigCategories.Recipes.storageblockcrafting, "tile.glowstone", false)) {
         GT_ModHandler.removeRecipe(new ItemStack[]{new ItemStack(Item.field_77751_aT, 1), new ItemStack(Item.field_77751_aT, 1), null, new ItemStack(Item.field_77751_aT, 1), new ItemStack(Item.field_77751_aT, 1)});
      }

      GT_ModHandler.addCompressionRecipe(new ItemStack(Item.field_77751_aT, 4, 0), new ItemStack(Block.field_72014_bd, 1));
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77760_aL, 1), Materials.Paper, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77823_bG, 1), Materials.Paper, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77821_bF, 1), Materials.Paper, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(GregTech_API.sBlockList[4], 1, 8), Materials.TungstenSteel, 3628800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(GregTech_API.sBlockList[0], 1, 2), Materials.Iridium, 3628800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(GregTech_API.sBlockList[4], 1, 9), Materials.Iridium, 3628800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(GregTech_API.sBlockList[4], 1, 13), Materials.Bronze, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77773_az, 1), Materials.Iron, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77788_aw, 1), Materials.Iron, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77766_aB, 1), Materials.Iron, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77721_bz, 1), Materials.Iron, 25401600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_72002_bp, 8), Materials.Iron, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_ModHandler.getIC2Item("ironFurnace", 1L), Materials.Iron, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_ModHandler.getIC2Item("ironFence", 1L), Materials.Iron, 1814400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Coin_Chocolate.get(1L, new Object[0]), Materials.Gold, 403200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Coin_Gold_Ancient.get(1L, new Object[0]), Materials.Gold, 907200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Coin_Doge.get(1L, new Object[0]), Materials.Brass, 907200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Credit_Greg_Cupronickel.get(1L, new Object[0]), Materials.Cupronickel, 907200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.IC2_Food_Can_Empty.get(1L, new Object[0]), Materials.Tin, 1814400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.IC2_Fuel_Rod_Empty.get(1L, new Object[0]), Materials.Iron, 3628800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.IC2_Fuel_Can_Empty.get(1L, new Object[0]), Materials.Tin, 25401600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Fuel_Can_Plastic_Empty.get(1L, new Object[0]), Materials.Plastic, 3628800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_94348_cl, 1), Materials.Gold, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_94345_cm, 1), Materials.Iron, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_82510_ck, 1, 0), Materials.Iron, 108864000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_82510_ck, 1, 1), Materials.Iron, 72576000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_82510_ck, 1, 2), Materials.Iron, 36288000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_ModHandler.getRecipeOutput(new ItemStack[]{GT_OreDictUnificator.get(OrePrefixes.block, (Object)Materials.Steel, 1L), GT_OreDictUnificator.get(OrePrefixes.block, (Object)Materials.Steel, 1L), GT_OreDictUnificator.get(OrePrefixes.block, (Object)Materials.Steel, 1L), null, GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Steel, 1L), null, GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Steel, 1L), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Steel, 1L), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Steel, 1L)}), Materials.Steel, 108864000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Block.field_94340_cs, 1), Materials.Iron, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(32, 1), Materials.Aluminium, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(33, 1), Materials.Bronze, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(34, 1), Materials.Brass, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(35, 1), Materials.Steel, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(36, 1), Materials.Titanium, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(37, 1), Materials.Iron, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(38, 1), Materials.TungstenSteel, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(39, 1), Materials.StainlessSteel, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(51, 1), Materials.Bronze, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(52, 1), Materials.Steel, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(53, 1), Materials.Magnalium, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GregTech_API.getGregTechComponent(54, 1), Materials.TungstenSteel, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Battery_Hull_LV.get(1L, new Object[0]), Materials.BatteryAlloy, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Battery_Hull_MV.get(1L, new Object[0]), Materials.BatteryAlloy, 21772800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Empty.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Mold_Gear.get(1L, new Object[0]), Materials.Steel, 14515200L, false);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Mold_Plate.get(1L, new Object[0]), Materials.Steel, 14515200L, false);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Mold_Casing.get(1L, new Object[0]), Materials.Steel, 14515200L, false);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Mold_Credit.get(1L, new Object[0]), Materials.Steel, 14515200L, false);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Plate.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Rod.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Bolt.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Ring.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Cell.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Ingot.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Wire.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Casing.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Block.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Pipe_Small.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Pipe_Medium.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Pipe_Large.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Gear.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Sword.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Shovel.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Hoe.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Axe.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Hammer.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Pickaxe.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_File.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Shape_Extruder_Saw.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Boiler.get(1L, new Object[0]), Materials.Bronze, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Furnace.get(1L, new Object[0]), Materials.Bronze, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_AlloySmelter.get(1L, new Object[0]), Materials.Bronze, 39916800L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Hammer.get(1L, new Object[0]), Materials.Bronze, 43545600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_CraftingTable.get(1L, new Object[0]), Materials.Bronze, 25401600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Macerator.get(1L, new Object[0]), Materials.Bronze, 43545600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Compressor.get(1L, new Object[0]), Materials.Bronze, 29030400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_Extractor.get(1L, new Object[0]), Materials.Bronze, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Bronze_BlastFurnace.get(1L, new Object[0]), Materials.Bronze, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Steel_Boiler.get(1L, new Object[0]), Materials.Steel, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Machine_Steel_Furnace.get(1L, new Object[0]), Materials.Steel, 14515200L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Frame_Iron.get(1L, new Object[0]), Materials.Iron, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Frame_Aluminium.get(1L, new Object[0]), Materials.Aluminium, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Frame_Steel.get(1L, new Object[0]), Materials.Steel, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Frame_StainlessSteel.get(1L, new Object[0]), Materials.StainlessSteel, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Frame_TungstenSteel.get(1L, new Object[0]), Materials.TungstenSteel, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_ModHandler.getIC2Item("machine", 1L), Materials.Iron, 29030400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_Items.Cell_Empty.get(1L, new Object[0]), Materials.Tin, 7257600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(GT_ModHandler.getRecipeOutput(new ItemStack[]{null, GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Tin, 1L), null, GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Tin, 1L), null, GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Tin, 1L), null, null, null}), Materials.Tin, 10886400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77694_Z, 4), Materials.Steel, 18144000L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77814_aa, 4), Materials.Steel, 29030400L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77816_ab, 4), Materials.Steel, 25401600L);
      GT_RecipeRegistrator.registerBasicReverseMaceratingAndSmelting(new ItemStack(Item.field_77810_ac, 4), Materials.Steel, 14515200L);
      GT_ModHandler.addSmeltingAndAlloySmeltingRecipe(new ItemStack(Item.field_77752_aS, 1), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Gold, 4L));
      GT_ModHandler.addSmeltingAndAlloySmeltingRecipe(new ItemStack(Item.field_77750_aQ, 1), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Iron, 4L));
      GT_ModHandler.addSmeltingAndAlloySmeltingRecipe(new ItemStack(Item.field_111215_ce, 1), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Iron, 8L));
      GT_ModHandler.addSmeltingAndAlloySmeltingRecipe(new ItemStack(Item.field_111216_cf, 1), GT_OreDictUnificator.get(OrePrefixes.ingot, (Object)Materials.Gold, 8L));
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_111215_ce, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Iron, 8L), new ItemStack(Item.field_77770_aF, 6), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_111216_cf, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Gold, 8L), new ItemStack(Item.field_77770_aF, 6), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_111213_cg, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Diamond, 8L), new ItemStack(Item.field_77770_aF, 6), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_77752_aS, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Gold, 4L), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Redstone, 1L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_77750_aQ, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Iron, 4L), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Redstone, 1L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72093_an, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Paper, 9L), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 6L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72096_bE, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Diamond, 2L), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Obsidian, 4L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72051_aB, 1), new ItemStack(Block.field_71939_E, 6), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72052_aC, 1), new ItemStack(Block.field_71939_E, 6), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72034_aR, 1), new ItemStack(Block.field_71939_E, 1), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_77792_au, 1, 0), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 2L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_77790_av, 1, 0), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 6L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72077_au, 1, 0), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 8L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_82511_ci, 1, 0), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 1L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72044_aK, 1), new ItemStack(Block.field_71939_E, 2), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72046_aM, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 2L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72035_aQ, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, (Object)Materials.Wood, 2L), new ItemStack(Item.field_77767_aC, 1), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72049_aP, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, (Object)Materials.Wood, 2L), new ItemStack(Item.field_77767_aC, 1), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72043_aJ, 1), new ItemStack(Block.field_71939_E, 1), GT_OreDictUnificator.get(OrePrefixes.dustSmall, (Object)Materials.Wood, 2L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Block.field_72055_aF, 1, 0), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 1L), (ItemStack)null, 0, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_82802_bI, 1, 0), new ItemStack(Item.field_77770_aF, 1), GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 4L), 95, false);
      GT_ModHandler.addPulverisationRecipe(new ItemStack(Item.field_77707_k, 1, 0), new ItemStack(Item.field_77683_K, 3), GT_OreDictUnificator.get(OrePrefixes.dustSmall, (Object)Materials.Wood, 3L), 95, false);
   }
}
