package gregtechmod.loaders.postload;

import gregtechmod.api.GregTech_API;
import gregtechmod.api.enums.GT_Items;
import gregtechmod.api.enums.Materials;
import gregtechmod.api.enums.OrePrefixes;
import gregtechmod.api.util.GT_Log;
import gregtechmod.api.util.GT_ModHandler;
import gregtechmod.api.util.GT_OreDictUnificator;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class GT_ScrapboxDropLoader implements Runnable {

   public void run() {
      GT_Log.out.println("GT_Mod: (re-)adding Scrapbox Drops.");
      GT_ModHandler.addScrapboxDrop(9.5F, new ItemStack(Item.field_77678_N));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Item.field_77712_u));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Item.field_77715_r));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Item.field_77714_s));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Item.field_77713_t));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Item.field_77792_au));
      GT_ModHandler.addScrapboxDrop(9.5F, new ItemStack(Item.field_77669_D));
      GT_ModHandler.addScrapboxDrop(5.0F, new ItemStack(Block.field_71979_v));
      GT_ModHandler.addScrapboxDrop(3.0F, new ItemStack(Block.field_71980_u));
      GT_ModHandler.addScrapboxDrop(3.0F, new ItemStack(Block.field_71940_F));
      GT_ModHandler.addScrapboxDrop(0.5F, new ItemStack(Block.field_72061_ba));
      GT_ModHandler.addScrapboxDrop(1.0F, new ItemStack(Block.field_72013_bc));
      GT_ModHandler.addScrapboxDrop(2.0F, new ItemStack(Block.field_72012_bb));
      GT_ModHandler.addScrapboxDrop(1.0F, new ItemStack(Item.field_77755_aX));
      GT_ModHandler.addScrapboxDrop(9.0F, new ItemStack(Item.field_77737_bm));
      GT_ModHandler.addScrapboxDrop(0.4F, new ItemStack(Item.field_77782_ar));
      GT_ModHandler.addScrapboxDrop(0.4F, new ItemStack(Item.field_77734_bj));
      GT_ModHandler.addScrapboxDrop(0.4F, new ItemStack(Item.field_77736_bl));
      GT_ModHandler.addScrapboxDrop(0.5F, new ItemStack(Item.field_77706_j));
      GT_ModHandler.addScrapboxDrop(0.5F, new ItemStack(Item.field_77684_U));
      GT_ModHandler.addScrapboxDrop(0.1F, new ItemStack(Item.field_77746_aZ));
      GT_ModHandler.addScrapboxDrop(1.0F, GT_Items.IC2_Food_Can_Filled.get(1L, new Object[0]));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_Items.IC2_Food_Can_Spoiled.get(1L, new Object[0]));
      GT_ModHandler.addScrapboxDrop(0.2F, GT_OreDictUnificator.get(OrePrefixes.cell, (Object)Materials.Silicon, 1L));
      GT_ModHandler.addScrapboxDrop(1.0F, GT_Items.Cell_Water.get(1L, new Object[0]));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_Items.Cell_Empty.get(1L, new Object[0]));
      GT_ModHandler.addScrapboxDrop(5.0F, GT_OreDictUnificator.get(OrePrefixes.plate, (Object)Materials.Paper, 1L));
      GT_ModHandler.addScrapboxDrop(1.0F, new ItemStack(Item.field_77770_aF));
      GT_ModHandler.addScrapboxDrop(1.0F, new ItemStack(Item.field_77676_L));
      GT_ModHandler.addScrapboxDrop(0.7F, GT_ModHandler.getIC2Item("plantBall", 1L));
      GT_ModHandler.addScrapboxDrop(3.8F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Wood, 1L));
      GT_ModHandler.addScrapboxDrop(0.6F, new ItemStack(Item.field_77761_aM));
      GT_ModHandler.addScrapboxDrop(0.8F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Rubber, 1L));
      GT_ModHandler.addScrapboxDrop(2.7F, GT_ModHandler.getIC2Item("suBattery", 1L));
      GT_ModHandler.addScrapboxDrop(0.8F, GregTech_API.getGregTechComponent(22, 1));
      GT_ModHandler.addScrapboxDrop(1.2F, GregTech_API.getGregTechComponent(24, 1));
      GT_ModHandler.addScrapboxDrop(1.8F, GregTech_API.getGregTechComponent(48, 1));
      GT_ModHandler.addScrapboxDrop(0.4F, GregTech_API.getGregTechComponent(49, 1));
      GT_ModHandler.addScrapboxDrop(0.2F, GregTech_API.getGregTechComponent(50, 1));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_ModHandler.getIC2Item("insulatedCopperCableItem", 1L));
      GT_ModHandler.addScrapboxDrop(0.4F, GT_ModHandler.getIC2Item("doubleInsulatedGoldCableItem", 1L));
      GT_ModHandler.addScrapboxDrop(0.9F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Redstone, 1L));
      GT_ModHandler.addScrapboxDrop(0.8F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Glowstone, 1L));
      GT_ModHandler.addScrapboxDrop(0.8F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Coal, 1L));
      GT_ModHandler.addScrapboxDrop(2.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Charcoal, 1L));
      GT_ModHandler.addScrapboxDrop(1.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Iron, 1L));
      GT_ModHandler.addScrapboxDrop(1.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Gold, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Silver, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Electrum, 1L));
      GT_ModHandler.addScrapboxDrop(1.2F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Tin, 1L));
      GT_ModHandler.addScrapboxDrop(1.2F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Copper, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Bauxite, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Aluminium, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Lead, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Nickel, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Zinc, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Brass, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Steel, 1L));
      GT_ModHandler.addScrapboxDrop(1.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Obsidian, 1L));
      GT_ModHandler.addScrapboxDrop(1.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Sulfur, 1L));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Saltpeter, 1L));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Lazurite, 1L));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Pyrite, 1L));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Calcite, 1L));
      GT_ModHandler.addScrapboxDrop(2.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Sodalite, 1L));
      GT_ModHandler.addScrapboxDrop(4.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Netherrack, 1L));
      GT_ModHandler.addScrapboxDrop(4.0F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Flint, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Platinum, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Tungsten, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Chrome, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Titanium, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Magnesium, 1L));
      GT_ModHandler.addScrapboxDrop(0.03F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.Endstone, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.GarnetRed, 1L));
      GT_ModHandler.addScrapboxDrop(0.5F, GT_OreDictUnificator.get(OrePrefixes.dust, (Object)Materials.GarnetYellow, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.Olivine, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.Ruby, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.Sapphire, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.GreenSapphire, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.Emerald, 1L));
      GT_ModHandler.addScrapboxDrop(0.05F, GT_OreDictUnificator.get(OrePrefixes.gem, (Object)Materials.Diamond, 1L));
   }
}
